version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: 487842886099
    AWS_DEFAULT_REGION: ap-northeast-1
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - BASE_DIR=`pwd`
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
  build:
    commands:
      - echo "Building spring-boot-batch !"
      - mvn clean package
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/spring-boot-batch:$IMAGE_TAG .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/spring-boot-batch:$IMAGE_TAG
      - cd $BASE_DIR
      - printf '[{"name":"spring-boot-batch","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/spring-boot-batch:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
