spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?preserveInstants=false&forceConnectionTimeZoneToSession=false
    username: user
    password: password
    driverClassName: com.mysql.jdbc.Driver
